### ISSUE TITLE
Stuck on 'Loading Profile' after signing in.

### ISSUE THREAD

**Issue by hearnia2k** [joshhunt/GhostOverlay#10]
Hello, 

This overlay looks super useful, however, no matter what I do I can't get it to work.

Software versions:
Windows 2004 19041.264
Game Bar 5.320.5221

I ave tried to login with Steam, and Xbox, and all seem to work, then get stuck saying "Loading Profile".

I've looked to try to find logs, but can't see any.  I ran wireshark to do some captures of the activity, and I see it doing a DNS lookup for bungie.net, and it gets an IPv4 and IPv6 replies, then appears to successfully communicate to the IPv6 address, of course, it's encrypted so I can't see what is being said.

If I look in my Bungie account I can see that I have the GhostOverlay as an Authorized Application.  I have tried to use teh reset option in Ghost Overlay, I have also tried to revoke the application from my Bungie account, and re-establish it, but the result is unchanged.

My account has 2 characters, one is basically never used, and old, and a more recent one, I created about a month back from memory.

I am happy to check logs and try things, provide information, etc, if it is helpful.

**Comment by hearnia2k** [comment]
Hmm, seems to be the same as https://github.com/joshhunt/GhostOverlay/issues/4

Sorry for the duplicate.  Enabling cross-save also fixed it for me.  I had Playstation linked, but with no characters.

**Comment by joshhunt** [comment]
Glad to hear - I'm still investigating this one.
