### ISSUE TITLE
Account Selection

### ISSUE THREAD

**Issue by Resef8604** [joshhunt/GhostOverlay#13]
I an only see my PS4 characters and not my PC characters.  I created a PC account before Cross Save was a thing and now I want to just see my PC characters, but all that comes up is PS4.  I cannot seem to see away to force it to view PC

**Comment by Resef8604** [comment]
If I need to do something at bungie.net let me know I guess.

**Comment by joshhunt** [comment]
At this time, I don't think I will add in account switching - the effort required to implement it means other things will always be prioritised over this. 

I have an update coming out that may alleviate this - when Ghost starts up it will select your most recently played account. Once that's live, let me know how it goes.

**Comment by Resef8604** [comment]
Thank you for you response.  As a work around for the issue I was able to unlink my playstation account at bungie.net and then log in via Steam.  I then restarted Ghost and it had the correct account quests and triumphs.  I then re-linked the playstation account.

> 
>
> At this time, I don't think I will add in account switching - the effort required to implement it means other things will always be prioritised over this.
> 
> I have an update coming out that may alleviate this - when Ghost starts up it will select your most recently played account. Once that's live (next few days?) let me know how it goes.

**Comment by ptaylor999** [comment]
Hey Josh,

 

Using GO like crazy, and lovin it. 

 

Only real issue is speed. I saw you have a new beta (1.3.4) that addresses this with a forced reload, that beta testers can try out? (didn’t see it on github) I’d love to get in on that. More than happy to provide any feedback you need,

Let me know what you think and how I should proceed.

 

Thanks!

 

Pat

**Comment by joshhunt** [comment]
The update should be out some time this week!

I'm not going to implement account switching, at least any time soon. I have an update out that will selected the most recent account, and I may make other tweaks to automatic account selection. If this is not helpful, I would recommend either to enable cross save or to do what you did and unlink/relink accounts.
