### ISSUE TITLE
English (Swedish) crashes Ghost when displaying bounties

### ISSUE THREAD

**Issue by Terkup** [joshhunt/GhostOverlay#14]
Windows 10, 2004. Same issue was also present on 1909 however, as I updated to see if anything changed.
If I start up the widget it initially crashes upon trying to display the pirsuits screen
![image](https://user-images.githubusercontent.com/20543006/84026374-81b7a300-a98d-11ea-8222-70a125debffe.png)

If I press restart it loads up an empty pursuits screen before promptly crashing again
![image](https://user-images.githubusercontent.com/20543006/84026490-b4619b80-a98d-11ea-9dca-05beb665f1a7.png)

If I quickly click on triumphs however, it will load up the initial triumph screen and my characters just fine, but any triumphs in those categories show up entirely blank and changing character does nothing except change which characters emblem I see in the top left.
![image](https://user-images.githubusercontent.com/20543006/84026581-de1ac280-a98d-11ea-9598-24c64a488651.png)
![image](https://user-images.githubusercontent.com/20543006/84026594-e410a380-a98d-11ea-9d80-c69bdfebb13f.png)

**Comment by Terkup** [comment]
Found where crashdumps are stored, in case these help you.
[CrashDumps.zip](https://github.com/joshhunt/GhostOverlay/files/4745750/CrashDumps.zip)

**Comment by meyer** [comment]
I'm experiencing this issue too, with English (South Africa). If I click around before the pursuits pane loads, I can view other things and change settings. As soon as I click the pursuits tab, I get the crash described above. Changing to en-US also fixes the issue for me.

**Comment by joshhunt** [comment]
This will be fixed in the next release!

**Comment by kaosmos** [comment]
Hello,
this issue is also (still) present if the first language is Italian:

![image](https://user-images.githubusercontent.com/138006/89498134-f193af80-d7bd-11ea-8ed5-2cb5113706e4.png)

![image](https://user-images.githubusercontent.com/138006/89498201-1ab44000-d7be-11ea-89a8-587c42b45095.png)

**Comment by Urim512** [comment]
i too am having issues i have my language set to english United States and it crashes when i try to add or remove things i am wanting to track like catalyst progress, quest progress, etc. it doesn't even let me get to a point where i can change anything or even open settings for it

**Comment by Urim512** [comment]
the moment i try to edit what i am tracking it starts to boot up the alt window and then crashes saying either something isn't playing nice or something else and i keep getting the option to either retry or restart please offer options to fix
