### ISSUE TITLE
Energy Weapon Catalyst crashes widget

### ISSUE THREAD

**Issue by bhwang1** [joshhunt/GhostOverlay#16]
Trying to access Energy Weapon Catalyst triumphs causes the widget to close and crash. Does not affect Kinetic or Power Weapon Catalyst triumphs

**Comment by joshhunt** [comment]
Dupe of #15. Annoyingly I have a fix for this which has passed certification, but I have to resubmit a new build because Microsoft delayed their update to Xbox Game Bar which the new version requires. Will be resubmitting a new build today, which should be out shortly.
