### ISSUE TITLE
GhostOverlay crashes if I go into Triumphs tab. Pursuits and Insights are fine.

### ISSUE THREAD

**Issue by hearnia2k** [joshhunt/GhostOverlay#18]
If I click to go to the Trimphs tab then the widget instantly crashes.

Sometimes the UI stops working, and other times it gives me a button to restart.  

If I click Triumphs quickly, before Pursits data shows up then it works as expected, unless I press the back button next to my characters name.

**Comment by fegkay15** [comment]
I am also experiencing this issue

**Comment by joshhunt** [comment]
What's your system language? This sounds similar to https://github.com/joshhunt/GhostOverlay/issues/14

**Comment by fegkay15** [comment]
For me personally mine is English (US). To specify how it is reacting differently than #14 , it loads perfectly everytime. It's only once I click the triumphs tab that it crashes. I am also able to get it to load if I click the restart button from the crash, then quickly click the triumphs tab before it finishes loading my profile. I have also noticed none of my friends are having this issue and this may be tied to something about my account as I can load the triumphs page if I do it before my profile finishes loading, which makes me think its related to my account. Also, I'm not sure it's related, but it looked like no data for different categories are showing up for me on the triumphs tab: 
![image](https://user-images.githubusercontent.com/13324054/87426108-c0ec9b80-c5ac-11ea-8fbc-fb4a52101132.png)

**Comment by hearnia2k** [comment]
My system is set to English US.  For what it's worth however, I am in the UK.

My experience as as described by fegkay15.  I believe all the data is loading, I can go through my triumphs and see things, and can select and track them, too.
His screenshot is consistent with my view, of course, there is a scroll bar to see more further down.

**Comment by joshhunt** [comment]
If you could visit this page https://ghostoverlay.com/debug and send me your _Profile_ data through gist.github.com it would be greatly appreciated to help me get to the bottom of this.

Cheers!

**Comment by hearnia2k** [comment]
How's this:  https://gist.github.com/hearnia2k/e30bd8fb74d44d2b0c7528e42170c084

**Comment by hearnia2k** [comment]
Also, for what it's worth, I'm a New Light player, having only played for about 4 month, and so don't likely have any super obscure old items.  Though, since I have been playing far too much I do have quite a few exotics, and things, but almost everything would have come from the current season.

**Comment by fegkay15** [comment]
https://gist.github.com/fegkay15/d3a0f8b4e2b04a760f45bce620d7f630

**Comment by joshhunt** [comment]
Thanks for this - im investigating now using your profile data. It's still early, but it appears there's a value missing that i expect to be there.

**Comment by joshhunt** [comment]
I'm not sure what causes this on Bungie's backend, but both your profiles had a progress of 0/0 on the "Moments of Triumph" D1 triumphs. Even though I started a fresh account (not a veteren account!) for D2 and have 0 progress here, my data is a bit different.

0 divided by 0 is bad for computers, hence the crash. 

This will be fixed in the next release, coming out next week or so.

**Comment by hearnia2k** [comment]
Thanks for the insights!  I saw the commit, and so figured it was something like that.
Though I am New Light, I played D1 in 2016, on PS4, and so I guess my profile has related data from that on it - hadn't realized D1 and D2 profiles were linked at all.
