### ISSUE TITLE
When a tracked quest changes step, can't seem to untrack it

### ISSUE THREAD

**Issue by Jakosaur** [joshhunt/GhostOverlay#19]
Means to an End was the quest when I experienced this.

When the quest step changed and Ghost updated, I couldn't untrack the quest by using the quests' right click menu. In the settings window, the quest wasn't tracked but tracking it again adds the quest onto the overlay alongside the previous one that can't be removed.

**Comment by joshhunt** [comment]
Thanks for a concrete repro! I'll take a look at this. In my head I think I can figure out what's causing this.

Cheers!
