### ISSUE TITLE
Keep getting "Something went wrong with this widget"

### ISSUE THREAD

**Issue by tpreston1989** [joshhunt/GhostOverlay#2]
I have tried restarting and reinstalling the widget a couple times now. Every time I go to "login to bungie" I keep getting that error and it only has the option to "restart." 

Not sure what to do at this point. Any ideas?

Also, I love the idea of this widget. Super pumped to use it.

**Comment by joshhunt** [comment]
In the meantime, try logging in with this link https://www.bungie.net/en/OAuth/Authorize?client_id=32459&response_type=code

**Comment by tpreston1989** [comment]
That worked! Thank you!
