### ISSUE TITLE
Triumph "Interference: Clear The Air" Missing

### ISSUE THREAD

**Issue by fegkay15** [joshhunt/GhostOverlay#20]
Self explanatory, triumph is missing in all 3 of the sections you would find it in: https://www.light.gg/db/legend/triumphs/112406565/interference-clear-the-air/

**Comment by joshhunt** [comment]
Behind the scenes, this triumph is character specific, and that part of my code wasnt working correctly. I suspect other character-specific triumphs might not have been working either. 

Anyway, sorted for next release. thanks for the report!
