### ISSUE TITLE
Crashes every time I try to open

### ISSUE THREAD

**Issue by SiddhardhaSaran** [joshhunt/GhostOverlay#31]
I have all the latest updates installed for windows ( 10.0.19042 Build 19042) and Xbox game bar. And whenever i try to open the settings page it crashes.

**Comment by MeridianPY** [comment]
Yup, I got the same issue. Would just like to bump this, because I don't know why this is happening or how to fix it.

**Comment by Scottkwiggins** [comment]
@SiddhardhaSaran @MeridianPY 
Would either of you happen to have your Windows Display Scale set to anything other than "100% (Recommended)"? I have found that I have to switch back to 100% when I'm going to use the overlay to keep it working reliably.

**Comment by MaverickRise** [comment]
@Scottkwiggins I couldn't use the overlay until I tried 100%, then it worked perfectly. Problem is I use an 4K UHD TV for my PC gaming, and use around 225% and 250% display setting for it being so big. 300% is actually recommended for my TV. I flipped through the sizes and 200% actually works fine and isn't too small for everyday use. Using a larger size would be nicer if possible!

**Comment by ryanbowden** [comment]
Oh nice for the fix!

Yes confirmed I had 150% on my Surface go 2. Changed it to 100% and now it works. Unreadable but it works. Wonder why the text increase crashes it.

**Comment by steveklabnik** [comment]
I can also confirm that I was having persistent crashes, but setting it to 100% fixed them. That said, it suggests 150% as the recommended setting, rather than 100%. It's tough to use my apps with it set to 100%, so hopefully this will get a fix at some point. If I knew anything about how this worked, I'd try to help...

**Comment by joshhunt** [comment]
Hey, just an update to say yes I see this, and I think I can replicate this myself so I’ll try and take a look at this soon!

**Comment by Scottkwiggins** [comment]
> Hey, just an update to say yes I see this, and I think I can replicate this myself so I’ll try and take a look at this soon!

Thank you so much Josh. That would be wonderful!

**Comment by ryanbowden** [comment]
BTW this looks like it is fixed @Scottkwiggins / @steveklabnik / @MaverickRise Working fine on my Surface go now set to 150%

**Comment by joshhunt** [comment]
Glad to hear!
