### ISSUE TITLE
Feature Request: Automatically Untrack Completed Bounties

### ISSUE THREAD

**Issue by canuckbrian** [joshhunt/GhostOverlay#35]
Right now tracked bounties stay in the widget once they're completed. It would be nice to have an option to automatically untrack them once they're completed. The reasoning behind this is when tracking a lot of bounties using the Overlay incomplete ones may be hidden further down and not visible unless you access the widget and scroll down, or manually untrack completed bounties.

**Comment by joshhunt** [comment]
complete bounties should be sorted to the bottom so they don’t obscure
incompleted ones. Is that not happening?

**Comment by canuckbrian** [comment]
My bad. You're right, the completed ones are moved to the bottom of the list and faded out. I was just dealing with a large list of bouinties (20+) and didn't see that they were doing that at first.
