### ISSUE TITLE
Widget hangs on login

### ISSUE THREAD

**Issue by Terri-bad** [joshhunt/GhostOverlay#4]
After logging in, the widget hangs on 'Loading Profile...'.
![Widget hangs on loading profile](https://user-images.githubusercontent.com/66129152/83274389-97092200-a182-11ea-9037-9afcc163f55c.png)

**Comment by drastikk** [comment]
I'm having this problem too. I want to use this so bad. Posting here to follow progress.

**Comment by maxlesser** [comment]
I am also having this issue. If there's any account info or repro I can provide to help track down what's happening, just let me know, I am happy to provide.

**Comment by joshhunt** [comment]
I wonder, what's your Bungie account situation? Have you enabled cross save? Do you have multiple platforms (Steam, Xbox, Playstation, etc) linked to your Bungie account?

**Comment by maxlesser-disney** [comment]
Played D1 on Xbox, so maybe that platform is linked to my bungie account. Everything since then has been PC, don't think I have enabled cross save (though maybe you had to do that when transitioning from Battle.net to steam?)

**Comment by maxlesser** [comment]
Played D1 on Xbox, so maybe that platform is linked to my bungie account. Everything since then has been PC, don't think I have enabled cross save (though maybe you had to do that when transitioning from Battle.net to steam?)

**Comment by Terri-bad** [comment]
I played D1 on XBOX, D2, on Battle.net before switching to Steam. I think I enabled Cross-Save, and I think I even linked Stadia when I did the free trial.

**Comment by joshhunt** [comment]
One thing I would just check, while i work on investigating, is *if you only play Destiny 2 on one platform* to enable Cross Save on your account and reset Ghost and try again.

My current hunch is that Ghost is having trouble picking the correct Destiny account, but I still need to investigate.

**Comment by drastikk** [comment]
I only played on Blizzard. I migrated my account to Steam during the handover but have never played D2 on another platform (I played D1 on PS3 but I don't think that would be relevant).

**Comment by Terri-bad** [comment]
Josh, after checking if I enabled Cross-Save, I found that I did not. I then proceeded to activate Cross-Save and chose my Steam account to be primary across all platforms and BOOM! Just like that, everything is working as it should. Correctly enabling Cross-Save was vital in fixing the issue of the "Loading Profile" hangup.

**Comment by drastikk** [comment]
I just did what Terri-bad said and it worked! I enabled cross-save from Steam to my Sony PS account (even though I haven't played since D1 on PS3) and it worked! Looks like that is the fix!

**Comment by maxlesser** [comment]
That did it for me as well!

**Comment by Terri-bad** [comment]
Activate Cross-Save, select your Primary Account, and enjoy this amazing widget.
