### ISSUE TITLE
Unable to sign into Steam to authorize app

### ISSUE THREAD

**Issue by Mvolk89** [joshhunt/GhostOverlay#48]
I was signed out of the app and trying to sign back into Steam to authorize the app does not show anything to click to sign in. It also does nothing when you try using desktop browser clicking that option.

![image](https://user-images.githubusercontent.com/98374393/223022922-4cffcd3d-3476-47ec-9a63-73d79f16d66c.png)

**Comment by CWSurpris3** [comment]
I had this visual issue as well. I was able to use the desktop option though.

**Comment by joshhunt** [comment]
Issue is with a combination of Steam and Microsoft's Web View they're using in Game Bar
