### ISSUE TITLE
wont let me install on microsoft store

### ISSUE THREAD

**Issue by 0rung** [joshhunt/GhostOverlay#5]
I went to the Microsoft store to download this, and the install button is greyed out. When I go to the library to try and install it, there is no install button. Instead, there is an exclamation point replacing it.

**Comment by fitzmill** [comment]
What version of Windows are you on? (version and OS build) You can find out by going to System -> About in the Settings app.

**Comment by 0rung** [comment]
Windows 10
Version : 1809
OS build : 17763.1217

**Comment by fitzmill** [comment]
I believe Xbox Game Bar widgets like Ghost Overlay are only supported on Windows versions 1903 and up. So if you want to be able to use the app you’ll have to upgrade your PC. Someone can correct me if I’m wrong.

**Comment by joshhunt** [comment]
Correct - @0rung you need Windows 1903 or 1909 with all installed windows updates https://docs.microsoft.com/en-us/gaming/game-bar/guide/windows-os
