### ISSUE TITLE
Widget crashes when trying to track bounties.

### ISSUE THREAD

**Issue by Puttzer** [joshhunt/GhostOverlay#7]
As the issue title says.

no amount of restarting widget helps.

Then theres the other issue of the widget connecting to the wrong platform. For some reason it keeps connecting to the playstation account not steam is there a way for me to change my platform?

EDIT:
Might be worth mentioning what version and OS build running
Version : 2004
OS build : 19041.264

**Comment by Puttzer** [comment]
> Then theres the other issue of the widget connecting to the wrong platform. For some reason it keeps connecting to the playstation account not steam is there a way for me to change my platform?


Got a workaround by unlinking my playstation account from my bungie account it now shows in settings the correct account.

It still crashes gamebar to either the game or desktop when i try to look at my pursuits or sometimes as soon as i start the app itself.

**Comment by joshhunt** [comment]
Do you see bounties/triumphs in the Settings widget?

I'm not personally running 2004 but there is a slim chance that might be causing issues that I havent tested?

> Then theres the other issue of the widget connecting to the wrong platform. For some reason it keeps connecting to the playstation account not steam is there a way for me to change my platform?

Yup - either unlink the platforms you don't play, or enable cross save. I'm not sure if I'll be able to prioritise platform switching any time soon.

**Comment by Puttzer** [comment]
Hi Sorry for the overdue response,

This is what i see, I can access triumphs but whenever i choose say "gambit lifetime" none of the triumphs in that category shows up.
![Overlay](https://user-images.githubusercontent.com/53831562/84578756-6ce17200-adc8-11ea-8586-092e69b688d7.png)

Settings can be also accessed with no issues.
![Overlay](https://user-images.githubusercontent.com/53831562/84578795-b92cb200-adc8-11ea-9ab4-b5c2ece59465.png)


It is whenever i try to acess pursuits tab it crashes the entire gamebar.

> I'm not personally running 2004 but there is a slim chance that might be causing issues that I havent tested?

The same issue persisted on the version previous to 2004. I updated in hope if by some miracle that would help.


Finally this is what i see when i restart xbox gamebar.
![Overlay](https://user-images.githubusercontent.com/53831562/84578858-407a2580-adc9-11ea-9b7d-6d10987372db.png)

**Comment by joshhunt** [comment]
Hey, sorry for the radio silence. Hope you're still around :) I'm thinking this might be similar to https://github.com/joshhunt/GhostOverlay/issues/14 ?

What's your language settings? If en-gb or en-us is not your highest priority, try changing to that and see if it changes things

**Comment by Puttzer** [comment]
#14 is def similar.Same Language settings,

Changing the language prefs did the trick i can now access everything without a crash. 

Is English(sweden) that more different than english(uk)?

Either way id say issue can be marked as resolved with that fix.

**Comment by joshhunt** [comment]
Yeah, I still need to investigate the issue to see what's happening. It's strange - it should work fine!
